# paths
data_dir: data
train_data_subdir: train
test_data_subdir: test
hyperparams_dir: hyperparams

# data generation
sample_to_subsample_size: 1000

# mlflow
tunning_experiment_name: tune_hyperparameters
training_experiment_name: training
scoring_experiment_name: scoring

# modeling
sample_sizes: [25, 50, 100]
train_samples_num: 100000
test_samples_num: 1000
models: [MLP] # Ridge, Lasso, DecisionTree, RandomForest, LightGBM, XGBoost, MLP

# tuning
cv_folds: 3
trials:
  Ridge: 30
  Lasso: 30
  DecisionTree: 60
  RandomForest: 60
  LightGBM: 80
  XGBoost: 80
  MLP: 60

# features
target_column: hurst

# randomization
random_seed: 42

# parallelization
n_jobs: 6
